console.log('I am linked now!');
let name="mhmd";
alert("My name is "+name);
let age;
var lastName;
const dob="30/12";
age=18;
lastName="sleimane";
console.log("lastname: "+lastName+"\n"+"age: "+age+"\n"+"day of birth is: "+dob);
let v1="This is a text";
let v2=true;
let v3={};
let v4=1215;
let v5="999";
let v6=null;
console.log(v1+": "+typeof(v1)+"\n"+v2+": "+typeof(v2)+"\n"+v3+": "+typeof(v3)+"\n"+v4+": "+typeof(v4)+"\n"+v5+": "+typeof(v5)+"\n"+v6+": "+typeof(v6));
let myText="keep trying";
let s1="way 1";
let s2='way 2';
let s3=`way 3`;
s1="way 1 ${myText}";
s2='way 2 ${myText}';
s3=`way 3 ${myText}`;
const tryThisAlso = `This is my new version, it’s the ${2 + 3}th version`;
console.log(s1);
console.log(s2);
console.log(s3);
console.log(tryThisAlso);
let S1="leo";
let S2="messi";
let result=S1+" "+S2;
console.log(result);
console.log(0==="0");
console.log(0!=="0");
console.log(0=="0");
console.log(0!="0");
console.log(9>8);
console.log(9>=9);
console.log(8<9);
console.log(8<="8");
let result0=5 + 3 * 2;
console.log(result0);
let result1=10 / 2 + 3;
let result2=10 / (2 + 3);
console.log(result2==result1);

